---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы 
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность сбросить фильтр
  - Сайт должен иметь пагинацию страниц
  - Количество добавленного товара в корзину можно изменить
  - Пользователю очевидно, что товар добавился в корзину
  - Пользователь должен иметь возможность удалить товар из корзины
  - Нельзя просматривать корзину другого пользователя
  - Сайт должен выдерживать нагрузку в 1000 посетителей онлайн одновременно
  - На сайте можно переключить язык на русский
  - Пользователь может продолжить выбирать товары после просмотра корзины
  - Информация об оформленном заказе передается на сервер

